env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "H9VcZuZR000FDnIr0gSHM9pdW6YMtIYHp4+zZBo1dxb3ZV59Ipje/GhGsqzWPpfe3zPHqTZWjodyRdUx7EeWd5AcQvhPJTazvxjhSr5dR7NQGGUdA0bD5iTSgkOgzKQ0vuCZg5NlYfWvrRB8leVVJKUiE0J+B5FRFhkB3RjP7n4="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "OpenKJ/OpenKJ"
      description: "Build submitted via Travis CI"
    notification_email: isaac@hozed.net
    build_command_prepend: "qmake; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install qt5-default qttools5-dev-tools qtbase5-dev qtmultimedia5-dev libqt5svg5-dev qttools5-dev qt5-qmake libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libqt5opengl5-dev libpulse-dev build-essential
script:
  - qmake
  - make -j4
